In [8]:
# The purpose on this is to practice more Python, besides the project contained on the other .ipynb file

In [14]:
num = 12
name = "Sam"
print("My number is {} and my name is {}".format(num,name))

My number is 12 and my name is Sam


In [17]:
S = "Hello"
S[4]

'o'

In [21]:
M = "abcdefghijk"
M[:4]

'abcd'

In [23]:
M[5:]

'fghijk'

In [25]:
M[1:4]

'bcd'

In [27]:
M[4]

'e'

In [28]:
# Las listas son secuencias de elementos separados por una coma
[1,2,3]

[1, 2, 3]

In [29]:
Mi_lista = ["a","b","c"]

In [30]:
Mi_lista 

['a', 'b', 'c']

In [31]:
Mi_lista.append("d")

In [32]:
Mi_lista

['a', 'b', 'c', 'd']

In [34]:
Mi_lista[3]

'd'

In [35]:
Mi_lista[0] = "Nuevo"

In [36]:
Mi_lista

['Nuevo', 'b', 'c', 'd']

In [40]:
# Listas nesteadas = son listas dentro de otras listas
nest = ["a","b","c",["d","e"]]
nest

['a']

In [46]:
d = {"key1":"value","key2":123}
d["key1"][0]

'v'

In [48]:
t = (1,2,3)
t[0]

1

In [50]:
# Devuelve los valores únicos
set([1,1,1,1,2,2,2,3,3])

{1, 2, 3}

In [52]:
1 > 2

False

In [54]:
1 <= 2

True

In [61]:
1 < 2 and 3 > 4

False

In [60]:
1 < 2 or 3 > 4 

True

In [63]:
1 < 2 and 3 > 4 and 1 == 3

False

In [69]:
if 1>2:
    print("yea!")
else:
    print("nope!")


nope!


In [71]:
seq = [1,2,3,4,5]

In [72]:
for item in seq:
    print(item)

1
2
3
4
5


In [73]:
for item in seq:
    print("hello!")

hello!
hello!
hello!
hello!
hello!


In [76]:
i = 1

while i < 5:
    print("i is: {}".format(i))
    i = i + 1

i is: 1
i is: 2
i is: 3
i is: 4


In [79]:
for x in seq:
    print(x ** 2)

1
4
9
16
25


In [83]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [84]:
x = [1,2,3,4]

In [86]:
out = []

for num in x:
    out.append(num**2)
print(out)


[1, 4, 9, 16]


In [93]:
def my_func(name):
    print("Hello "+name)

In [95]:
my_func("John")

Hello John


In [97]:
def square(num):
    return num**2

output= square(2)
print(output)

4


In [1]:
def times2(var):
    return var*2

times2(5)

10

In [3]:
seq = [1,2,3,4,5]
list(map(lambda num: num*3,seq))

[3, 6, 9, 12, 15]

In [5]:
list(filter(lambda num: num%2 == 0, seq))

[2, 4]

In [6]:
W = "Hello my name is Sam"

In [8]:
W.capitalize()

'Hello my name is sam'

In [9]:
W.lower()

'hello my name is sam'

In [10]:
W.upper()

'HELLO MY NAME IS SAM'

In [11]:
W.split() # Este es util para analisis de datos de cadenas de texto.

['Hello', 'my', 'name', 'is', 'Sam']

In [13]:
tweet="Go! sports! #Sports"
tweet.split("#")[1]

'Sports'

In [14]:
d = {"k1": 1,"k2":2}


{'k1': 1, 'k2': 2}

In [15]:
d.keys()

dict_keys(['k1', 'k2'])

In [16]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [18]:
d.values() # No mantiene el orden, considerar

dict_values([1, 2])

In [21]:
"X" in ["X","y","z"] # Sí considera las mayusculas

True

In [23]:
X = [(1,2),(3,4),(5,6)]

In [34]:
for (a,b) in X:
    if b > 2:
        print("yay! your number is {}".format(a,b))
    else:
        print(a)

1
yay! your number is 3
yay! your number is 5


In [2]:
def caught_speeding(speed, is_birthday):
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed
    
    if speeding > 80:
        return "Big ticket"
    elif speeding > 60:
        return "Small ticket"
    else:
        return "No ticket"
    

In [11]:
caught_speeding(15,False)

'No ticket'

In [3]:
# Introduction to libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [13]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [14]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(5)

array([0.48629757, 0.889067  , 0.45759052, 0.01113102, 0.09154094])

In [28]:
np.random.rand(5,5)

array([[0.06259933, 0.97756681, 0.95284482, 0.70328403, 0.964399  ],
       [0.18985754, 0.29989721, 0.56719542, 0.84785407, 0.02817735],
       [0.89806866, 0.85510475, 0.45236892, 0.99067284, 0.9263557 ],
       [0.73921237, 0.71322774, 0.50496753, 0.05307387, 0.77901255],
       [0.6444801 , 0.94289445, 0.09859168, 0.77515454, 0.89342537]])

In [30]:
np.random.randn(4,4)

array([[-0.19916368, -0.37886761,  0.79038611, -0.1103673 ],
       [-1.36598551, -0.68766821,  0.82362744, -1.09134069],
       [-0.29760897, -1.56721733,  0.60259412, -0.01135395],
       [-1.76569226,  1.56921918,  0.5398106 , -0.01526203]])

In [47]:
np.random.randint(1,100,10)

array([78, 34, 71, 23,  5, 31, 37, 12,  9, 43])

In [49]:
arr = np.arange(25)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
ranarr = np.random.randint(0,50,10)

In [53]:
ranarr

array([ 1, 46,  6, 44, 43, 12, 47,  6, 32, 38])

In [55]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
ranarr.max()

47

In [59]:
ranarr.min()

1

In [60]:
ranarr.mean()

27.5

In [61]:
ranarr.std()

17.979154596365202

In [62]:
ranarr.var()

323.25

In [63]:
ranarr.argmax() # Parte desde el 0

6

In [9]:
arr = np.arange(0,11)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[8]

8

In [67]:
arr[1:5]

array([1, 2, 3, 4])

In [69]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [70]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [73]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [75]:
arr[0:5] = 100

In [76]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [77]:
arr = np.arange(0,11)

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
slice_of_arr = arr[0:6]

In [80]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [83]:
slice_of_arr[:] = 99

In [84]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [85]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [86]:
arr_copy = arr.copy()

In [87]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [88]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [89]:
arr_copy[:]=100

In [90]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [91]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [92]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [93]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [95]:
arr_2d[0][2] # Mirar linea 101, entrega [columna][fila]

15

In [96]:
arr_2d[0]

array([ 5, 10, 15])

In [101]:
arr_2d[2,1] # Es otra alternativa

40

In [102]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [104]:
arr = np.arange(1,11)

In [105]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [107]:
bool_arr = arr > 5

In [108]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [109]:
arr[arr>5] # Es lo mismo que el anterior

array([ 6,  7,  8,  9, 10])

In [110]:
arr_2d = np.arange(50).reshape(5,10)

In [111]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [113]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [1]:
arr_2d + arr

NameError: name 'arr_2d' is not defined

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [12]:
np.mean(arr)

5.0

In [13]:
np.log(arr)

C:\Users\phyrx\AppData\Local\Temp\ipykernel_9192\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [3]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
np.arange(10,51,2) 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.rand(1)

array([0.37448151])

In [27]:
np.random.randn(25).reshape(5,5)

array([[-1.41563466, -0.75398443,  0.10657337,  0.80210703,  1.69844398],
       [ 0.7385425 , -1.01628274, -0.12558637,  0.0868879 ,  0.65898357],
       [ 0.02934528,  1.16017136,  1.33131811, -0.45705542, -1.6467263 ],
       [ 0.13571462,  2.41255336,  0.16724023, -1.36974   , -1.73660949],
       [-0.57946505, -1.20614016, -1.77191987,  0.43775928, -1.58841508]])

In [31]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [32]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [33]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [4]:
labels = ["a","b","c"]
my_data = [10,20,30]
arr = np.array(my_data)
d = {"a":10,"b":20,"c":30}

In [46]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [47]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(data=[my_data,print,len])

0                 [10, 20, 30]
1    <built-in function print>
2      <built-in function len>
dtype: object

In [6]:
ser3 = pd.Series(data=my_data)

In [7]:
ser3[2]

30

In [4]:
from numpy.random import randn

In [9]:
np.random.seed(101)

In [76]:
df = pd.DataFrame(randn(5,4),["A","B","C","D","E"],["W","X","Y","Z"])

In [77]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [12]:
df["W"]

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [13]:
type(df["W"])

pandas.core.series.Series

In [14]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df["X"]

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [17]:
df["new"] = df["W"] + df["Y"]

In [18]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [21]:
df.drop("new",axis=1,inplace=True)

In [22]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [25]:
df.drop("E", inplace=True)

In [27]:
df.shape

(4, 4)

In [37]:
df[3:4]

W         X         Y         Z
D  0.188695 -0.758872 -0.933237  0.955057

In [38]:
df.loc["A"]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [39]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [40]:
df.loc["B","Y"]

-0.8480769834036315

In [41]:
df.loc[["A","B"],["W","Y"]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [43]:
df > 0 

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True

In [44]:
df == 0

W      X      Y      Z
A  False  False  False  False
B  False  False  False  False
C  False  False  False  False
D  False  False  False  False

In [45]:
df < 0

W      X      Y      Z
A  False  False  False  False
B  False   True   True  False
C   True  False  False   True
D  False   True   True  False

In [46]:
booldf = df > 0

In [47]:
booldf

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True

In [48]:
df[booldf]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057

In [49]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057

In [50]:
df["W"]>0

A     True
B     True
C    False
D     True
Name: W, dtype: bool

In [53]:
df[df["W"] > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [54]:
df[df["Z"]<0]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [55]:
resultdf = df[df["W"]>0]

In [56]:
resultdf["X"]

A    0.628133
B   -0.319318
D   -0.758872
Name: X, dtype: float64

In [59]:
df[df["W"]>0][["Y","X"]]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872

In [68]:
boolser = df["W"]>0
result = df[boolser]
mycols = ["Y","X"]
result[mycols]

Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872

In [70]:
result

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [79]:
df[(df["W"]>0) | (df["Y"]>1)]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [80]:
df 

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [81]:
df.reset_index()

index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [82]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [83]:
newind = "CA NY WY OR CO".split()

In [84]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [85]:
df["States"] = newind

In [86]:
df.set_index("States")

W         X         Y         Z
States                                        
CA      0.302665  1.693723 -1.706086 -1.159119
NY     -0.134841  0.390528  0.166905  0.184502
WY      0.807706  0.072960  0.638787  0.329646
OR     -0.497104 -0.754070 -0.943406  0.484752
CO     -0.116773  1.901755  0.238127  1.996652

In [87]:
df

W         X         Y         Z States
A  0.302665  1.693723 -1.706086 -1.159119     CA
B -0.134841  0.390528  0.166905  0.184502     NY
C  0.807706  0.072960  0.638787  0.329646     WY
D -0.497104 -0.754070 -0.943406  0.484752     OR
E -0.116773  1.901755  0.238127  1.996652     CO

In [88]:
outside = ["G1","G1","G1","G2","G2","G2"]
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [90]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [91]:
df = pd.DataFrame(randn(6,2),hier_index,["A","B"])

In [92]:
df

A         B
G1 1 -0.993263  0.196800
   2 -1.136645  0.000366
   3  1.025984 -0.156598
G2 1 -0.031579  0.649826
   2  2.154846 -0.610259
   3 -0.755325 -0.346419

In [93]:
df.loc["G1"]

A         B
1 -0.993263  0.196800
2 -1.136645  0.000366
3  1.025984 -0.156598

In [97]:
df.loc["G2"].loc[2]["B"]

-0.6102588558227414

In [98]:
df.xs("G1")

A         B
1 -0.993263  0.196800
2 -1.136645  0.000366
3  1.025984 -0.156598

In [102]:
d = {"A":[1,2,np.nan],"B":[5,np.nan,np.nan],"C":[1,2,3]}

In [103]:
df = pd.DataFrame(d)

In [104]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [106]:
df.dropna(axis=1) # Elimina columnas

C
0  1
1  2
2  3

In [107]:
df.dropna() # Elimina filas

A    B  C
0  1.0  5.0  1

In [110]:
df.dropna(thresh=2) # Al menos 2 NA values

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [111]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [112]:
df.fillna(value="FILL VALUE")

A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [114]:
df["A"].fillna(value=df["A"].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [115]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [130]:
data = {"Company":["GOOG","GOOG","MSFT","MSFT","FB","FB"],
        "Person":["Sam","Charlie","Amy","Vanessa","Carl","Sarah"],
        "Sales":[200,120,340,124,243,350]}

In [135]:
df = pd.DataFrame(data)

In [138]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [140]:
byComp = df.groupby("Company")

In [145]:
byComp.mean("Company")

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [146]:
byComp.sum("Sales")

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [153]:
byComp.describe().transpose()["FB"]

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

In [7]:
df1 = pd.DataFrame(

    {

        "A": ["A0", "A1", "A2", "A3"],

        "B": ["B0", "B1", "B2", "B3"],

        "C": ["C0", "C1", "C2", "C3"],

        "D": ["D0", "D1", "D2", "D3"],

    },

    index=[0, 1, 2, 3],

)



df2 = pd.DataFrame(

    {

        "A": ["A4", "A5", "A6", "A7"],

        "B": ["B4", "B5", "B6", "B7"],

        "C": ["C4", "C5", "C6", "C7"],

        "D": ["D4", "D5", "D6", "D7"],

    },

    index=[4, 5, 6, 7],

)



df3 = pd.DataFrame(

    {

        "A": ["A8", "A9", "A10", "A11"],

        "B": ["B8", "B9", "B10", "B11"],

        "C": ["C8", "C9", "C10", "C11"],

        "D": ["D8", "D9", "D10", "D11"],

    },

    index=[8, 9, 10, 11],

)


In [155]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [156]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [157]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [158]:
left = pd.DataFrame(

    {

        "key": ["K0", "K1", "K2", "K3"],

        "A": ["A0", "A1", "A2", "A3"],

        "B": ["B0", "B1", "B2", "B3"],

    }

)



right = pd.DataFrame(

    {

        "key": ["K0", "K1", "K2", "K3"],

        "C": ["C0", "C1", "C2", "C3"],

        "D": ["D0", "D1", "D2", "D3"],

    }

)

In [159]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [160]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [161]:
pd.merge(left,right,how="inner",on="key")

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [162]:
left = pd.DataFrame(

   {

      "key1": ["K0", "K0", "K1", "K2"],

      "key2": ["K0", "K1", "K0", "K1"],

      "A": ["A0", "A1", "A2", "A3"],

      "B": ["B0", "B1", "B2", "B3"],

   }

)



right = pd.DataFrame(

   {

      "key1": ["K0", "K1", "K1", "K2"],

      "key2": ["K0", "K0", "K0", "K0"],

      "C": ["C0", "C1", "C2", "C3"],

      "D": ["D0", "D1", "D2", "D3"],

   }

)


In [163]:
pd.merge(left,right,on=["key1","key2"])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [164]:
pd.merge(left,right,how="outer",on=["key1","key2"])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [165]:
pd.merge(left,right,how="left",on=["key1","key2"])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [166]:
pd.merge(left,right,how="right",on=["key1","key2"])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [5]:
def times2(x):
    return x*2

In [9]:
df1["A"].apply(times2) # Recordar la función Inplace

0    A0A0
1    A1A1
2    A2A2
3    A3A3
Name: A, dtype: object

In [11]:
df1.index

Index([0, 1, 2, 3], dtype='int64')

In [12]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [16]:
df1.sort_values("B")

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [17]:
df1.isnull()

A      B      C      D
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False

In [25]:
pwd

'e:\\Repo GitHub\\Data Analysis'

In [27]:
train = pd.read_csv("E:/Repo GitHub/Data Analysis/datasets/train.csv")
test = pd.read_csv("E:/Repo GitHub/Data Analysis/datasets/test.csv")

In [28]:
train.to_csv("My_output",index=False)

In [29]:
train

date  store  item  sales
0       2013-01-01      1     1     13
1       2013-01-02      1     1     11
2       2013-01-03      1     1     14
3       2013-01-04      1     1     13
4       2013-01-05      1     1     10
...            ...    ...   ...    ...
912995  2017-12-27     10    50     63
912996  2017-12-28     10    50     59
912997  2017-12-29     10    50     74
912998  2017-12-30     10    50     62
912999  2017-12-31     10    50     82

[913000 rows x 4 columns]

In [41]:
import sqlalchemy
import lxml
import html5lib


In [45]:
htmldata = pd.read_html("https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/")

In [46]:
htmldata

[                             Bank NameBank       CityCity StateSt  CertCert  \
 0    Republic First Bank dba Republic Bank   Philadelphia      PA     27332   
 1                            Citizens Bank       Sac City      IA      8758   
 2                 Heartland Tri-State Bank        Elkhart      KS     25851   
 3                      First Republic Bank  San Francisco      CA     59017   
 4                           Signature Bank       New York      NY     57053   
 ..                                     ...            ...     ...       ...   
 564                     Superior Bank, FSB       Hinsdale      IL     32646   
 565                    Malta National Bank          Malta      OH      6629   
 566        First Alliance Bank & Trust Co.     Manchester      NH     34264   
 567      National State Bank of Metropolis     Metropolis      IL      3815   
 568                       Bank of Honolulu       Honolulu      HI     21029   
 
                  Acquiring Institutio

In [47]:
from sqlalchemy import create_engine

In [48]:
engine = create_engine("sqlite:///:memory:")

In [49]:
train.to_sql("my_table", engine)

913000

In [50]:
sqldf = pd.read_sql("my_table", con=engine)

In [51]:
sqldf

index        date  store  item  sales
0            0  2013-01-01      1     1     13
1            1  2013-01-02      1     1     11
2            2  2013-01-03      1     1     14
3            3  2013-01-04      1     1     13
4            4  2013-01-05      1     1     10
...        ...         ...    ...   ...    ...
912995  912995  2017-12-27     10    50     63
912996  912996  2017-12-28     10    50     59
912997  912997  2017-12-29     10    50     74
912998  912998  2017-12-30     10    50     62
912999  912999  2017-12-31     10    50     82

[913000 rows x 5 columns]

In [5]:
salaries = pd.read_csv("E:\Repo GitHub\Data Analysis\datasets\Salaries.csv")

C:\Users\phyrx\AppData\Local\Temp\ipykernel_14244\2631785553.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  salaries = pd.read_csv("E:\Repo GitHub\Data Analysis\datasets\Salaries.csv")


In [54]:
salaries

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle       BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY     167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)     155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)     212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC       77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)      134401.6   
...                                                ...           ...   
148649                                       Custodian          0.00   
148650                                    Not provided  Not Provided   
148651                                    Not provided  Not Provided   
148652                                    Not provided  Not Provided   
148653                      Counselor, Log Cabin Ranch          0.00   

         OvertimePay      OtherPay      Benefits   TotalPay  TotalPayBenefits  \
0                0.0     400184.25           NaN  567595.43         567595.43   
1          245131.88     137811.38           NaN  538909.28         538909.28   
2          106088.18       16452.6           NaN  335279.91         335279.91   
3           56120.71      198306.9           NaN  332343.61         332343.61   
4             9737.0     182234.59           NaN  326373.19         326373.19   
...              ...           ...           ...        ...               ...   
148649          0.00          0.00          0.00       0.00              0.00   
148650  Not Provided  Not Provided  Not Provided       0.00              0.00   
148651  Not Provided  Not Provided  Not Provided       0.00              0.00   
148652  Not Provided  Not Provided  Not Provided       0.00              0.00   
148653          0.00       -618.13          0.00    -618.13           -618.13   

        Year  Notes         Agency Status  
0       2011    NaN  San Francisco    NaN  
1       2011    NaN  San Francisco    NaN  
2       2011    NaN  San Francisco    NaN  
3       2011    NaN  San Francisco    NaN  
4       2011    NaN  San Francisco    NaN  
...      ...    ...            ...    ...  
148649  2014    NaN  San Francisco     PT  
148650  2014    NaN  San Francisco    NaN  
148651  2014    NaN  San Francisco    NaN  
148652  2014    NaN  San Francisco    NaN  
148653  2014    NaN  San Francisco     PT  

[148654 rows x 13 columns]

In [57]:
salaries["JobTitle"]

0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                        CAPTAIN III (POLICE DEPARTMENT)
2                        CAPTAIN III (POLICE DEPARTMENT)
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
                               ...                      
148649                                         Custodian
148650                                      Not provided
148651                                      Not provided
148652                                      Not provided
148653                        Counselor, Log Cabin Ranch
Name: JobTitle, Length: 148654, dtype: object

In [62]:
salaries[salaries["EmployeeName"] == "JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [64]:
salaries[salaries["EmployeeName"] == "JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [68]:
salaries[salaries["TotalPayBenefits"] == salaries["TotalPayBenefits"].max()]["EmployeeName"]

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [70]:
salaries.loc[salaries["TotalPayBenefits"].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

In [71]:
salaries.iloc[salaries["TotalPayBenefits"].argmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

In [73]:
salaries.iloc[salaries["TotalPayBenefits"].argmin()]

Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                   0.00
OvertimePay                               0.00
OtherPay                               -618.13
Benefits                                  0.00
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                      PT
Name: 148653, dtype: object

In [6]:
sum(salaries[salaries["Year"]==2013]["JobTitle"].value_counts()==1)

202

In [7]:
def chief_string(title):
    if "chef" in title.lower().split():
        return True
    else:
        return False

In [9]:
salaries["JobTitle"].iloc[0]

'GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY'

In [14]:
chief_string('chEf GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY')

True

In [15]:
salaries["title_len"] = salaries["JobTitle"].apply(len)

In [16]:
salaries[["JobTitle","title_len"]]

JobTitle  title_len
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY         46
1                      CAPTAIN III (POLICE DEPARTMENT)         31
2                      CAPTAIN III (POLICE DEPARTMENT)         31
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC         36
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)         44
...                                                ...        ...
148649                                       Custodian          9
148650                                    Not provided         12
148651                                    Not provided         12
148652                                    Not provided         12
148653                      Counselor, Log Cabin Ranch         26

[148654 rows x 2 columns]

In [20]:
ecom = pd.read_csv("E:/Repo GitHub/Data Analysis/datasets/Ecommerce Purchases.csv")

In [21]:
ecom

Address    Lot AM or PM  \
0     16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1     9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                      Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3                 7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4     23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   
...                                                 ...    ...      ...   
9995      966 Castaneda Locks\nWest Juliafurt, CO 96415  92 XI       PM   
9996  832 Curtis Dam Suite 785\nNorth Edwardburgh, T...  41 JY       AM   
9997              Unit 4434 Box 6343\nDPO AE 28026-0283  74 Zh       AM   
9998               0096 English Rest\nRoystad, IA 12457  74 cL       PM   
9999     40674 Barrett Stravenue\nGrimesville, WI 79682  64 Hr       AM   

                                           Browser Info  \
0     Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1     Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2     Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4     Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   
...                                                 ...   
9995  Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...   
9996  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
9997  Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...   
9998  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...   
9999  Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...   

                              Company       Credit Card CC Exp Date  \
0                     Martinez-Herman  6011929061123406       02/20   
1     Fletcher, Richards and Whitaker  3337758169645356       11/18   
2          Simpson, Williams and Pham      675957666125       08/19   
3     Williams, Marshall and Buchanan  6011578504430710       02/24   
4           Brown, Watson and Andrews  6011456623207998       10/25   
...                               ...               ...         ...   
9995                    Randall-Sloan   342945015358701       03/22   
9996         Hale, Collins and Wilson   210033169205009       07/25   
9997                     Anderson Ltd  6011539787356311       05/21   
9998                         Cook Inc   180003348082930       11/17   
9999                       Greene Inc  4139972901927273       02/19   

      CC Security Code                  CC Provider  \
0                  900                 JCB 16 digit   
1                  561                   Mastercard   
2                  699                 JCB 16 digit   
3                  384                     Discover   
4                  678  Diners Club / Carte Blanche   
...                ...                          ...   
9995               838                 JCB 15 digit   
9996               207                 JCB 16 digit   
9997                 1                VISA 16 digit   
9998               987             American Express   
9999               302                 JCB 15 digit   

                               Email                                     Job  \
0                  pdunlap@yahoo.com  Scientist, product/process development   
1                 anthony41@reed.com                       Drilling engineer   
2     amymiller@morales-harrison.com                Customer service manager   
3        brent16@olson-robinson.info                       Drilling engineer   
4        christopherwright@gmail.com                             Fine artist   
...                              ...                                     ...   
9995          iscott@wade-garner.com                              Printmaker   
9996              mary85@hotmail.com                         Energy engineer   
9997               tyler16@gmail.com                      Veterinary surgeon   
9998         elizabethmoore@reid.net                Local government officer   
9999           rachelford@vaughn.com        

In [22]:
ecom.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

In [24]:
len(ecom.index)

10000

In [25]:
ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Address           10000 non-null  object 
 1   Lot               10000 non-null  object 
 2   AM or PM          10000 non-null  object 
 3   Browser Info      10000 non-null  object 
 4   Company           10000 non-null  object 
 5   Credit Card       10000 non-null  int64  
 6   CC Exp Date       10000 non-null  object 
 7   CC Security Code  10000 non-null  int64  
 8   CC Provider       10000 non-null  object 
 9   Email             10000 non-null  object 
 10  Job               10000 non-null  object 
 11  IP Address        10000 non-null  object 
 12  Language          10000 non-null  object 
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [26]:
ecom.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [27]:
ecom["Purchase Price"].mean()

50.347302

In [30]:
ecom["Purchase Price"].max()

99.99

In [29]:
ecom["Purchase Price"].min()

0.0

In [31]:
ecom.head(3)

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   

   CC Security Code   CC Provider                           Email  \
0               900  JCB 16 digit               pdunlap@yahoo.com   
1               561    Mastercard              anthony41@reed.com   
2               699  JCB 16 digit  amymiller@morales-harrison.com   

                                      Job       IP Address Language  \
0  Scientist, product/process development  149.146.147.205       el   
1                       Drilling engineer     15.160.41.51       fr   
2                Customer service manager   132.207.160.22       de   

   Purchase Price  
0           98.14  
1           70.73  
2            0.95

In [36]:
ecom[ecom["Language"] == "en"]["Language"].count()

1098

In [38]:
ecom[ecom["Job"] == "Lawyer"].count()

Address             30
Lot                 30
AM or PM            30
Browser Info        30
Company             30
Credit Card         30
CC Exp Date         30
CC Security Code    30
CC Provider         30
Email               30
Job                 30
IP Address          30
Language            30
Purchase Price      30
dtype: int64